### ISSUE TITLE
How to use it?!

### ISSUE THREAD

**Issue by reza7rm** [lucbelliveau/react-native-dtmf#1]
I really have no idea how I can use this library? I have written a simple code using react-native-immediate-phone-call which causes the dialer to appear, I used background task and libraries like react-native-background-timer to be able to dial dtmf tones after dialing a number but it seesm they do not work in background and as there's no way, as far as I know, to prevent the dialer comes up I am wondering if there's a sample code of this library that actually works?

**Comment by lucbelliveau** [comment]
The library isn't designed to interact with any other libraries or components... it simply emits tones out of the speaker.  If you were implementing your own custom dialer for example, and you wanted it to make the tones as the user presses the buttons, you would use this library.
